test3

diff --git a/sbin/dockerbox b/sbin/dockerbox
--- a/sbin/dockerbox
+++ b/sbin/dockerbox
@@ -55,9 +55,9 @@ log() {
     local _message="$2"
     local _timestamp
 
-    _level="$(${ECHO} $_level | tr "[:lower:]" "[:upper:]")"
+    _level="$(${ECHO} "$_level" | tr "[:lower:]" "[:upper:]")"
     _timestamp="$(date +'%FT%H:%M:%S%z')"
-    ${ECHO} "${_timestamp} ${_level} ${_message}" >>${DOCKERBOX_LOG}
+    ${ECHO} "${_timestamp} ${_level} ${_message}" >>"${DOCKERBOX_LOG}"
 }
 
 output() {
@@ -102,8 +102,8 @@ get_tap_interface() {
 }
 
 check_ext_if() {
-    . ${CONFIG}
-    ${IFCONFIG} | ${GREP} ${ext_if} -c
+    . "${CONFIG}"
+    ${IFCONFIG} | ${GREP} "${ext_if}" -c
 }
 
 assert_kmod_loaded() {
@@ -134,7 +134,7 @@ nat_count() {
     local _nat_keyword="$1"
     local _ext_if="$2"
     log debug "assert NAT loaded: nat_if=${_nat_keyword} ext_if=${_ext_if}"
-    ${PFCTL} -s nat | ${GREP} nat | ${GREP} ${_nat_keyword} | ${GREP} ${_ext_if} -c
+    ${PFCTL} -s nat | ${GREP} nat | ${GREP} "${_nat_keyword}" | ${GREP} "${_ext_if}" -c
 }
 
 check_pf() {
@@ -148,28 +148,28 @@ check_pf() {
     if [ ! -f "${PF_CONF}" ]; then
         log warn "No pf configuration found"
         log info "Creating empty pf configuration ${PF_CONF}"
-        ${TOUCH} ${PF_CONF}
+        ${TOUCH} "${PF_CONF}"
     fi
-    check_configuration ${CONFIG}
+    check_configuration "${CONFIG}"
 
     nat_ip="10.0.0.1"
     nat_mask=24
 
     log info "Pulling options from configuration file"
-    . ${CONFIG}
+    . "${CONFIG}"
 
-    nat_keyword="$(echo ${nat_ip} | cut -d'.' -f1-3).0/${nat_mask}"
+    nat_keyword="$(echo "${nat_ip}" | cut -d'.' -f1-3).0/${nat_mask}"
 
-    if [ "$(nat_count ${nat_keyword} ${ext_if})" -lt 1 ]; then
+    if [ "$(nat_count "${nat_keyword}" "${ext_if}")" -lt 1 ]; then
         log warn "No pf NAT set up"
         if [ "$(check_ext_if)" -lt 1 ]; then
             log warn "External interface specified in settings not available"
         else
             log info "Writing NAT rule into ${PF_CONF}"
-            ${ECHO} "nat on ${ext_if} inet from ${nat_keyword} to any -> (${ext_if})" >>${PF_CONF}
+            ${ECHO} "nat on ${ext_if} inet from ${nat_keyword} to any -> (${ext_if})" >>"${PF_CONF}"
             log info "Loading pf conf ${PF_CONF}"
-            ${PFCTL} -f ${PF_CONF}
-            if [ "$(nat_count ${nat_keyword} ${ext_if})" -lt 1 ]; then
+            ${PFCTL} -f "${PF_CONF}"
+            if [ "$(nat_count "${nat_keyword}" "${ext_if}")" -lt 1 ]; then
                 log warn "Failed to load pf NAT with ${PF_CONF}"
             fi
         fi
@@ -179,26 +179,26 @@ check_pf() {
 create_bridge() {
     if ! has_bridge_interface; then
         log info "Creating bridge interface: ${DOCKERBOX_IF}"
-        ${IFCONFIG} bridge create name ${DOCKERBOX_IF} up 2>&1 | capture_output debug ifconfig
+        ${IFCONFIG} bridge create name "${DOCKERBOX_IF}" up 2>&1 | capture_output debug ifconfig
     else
         log warn "Bridge interface already exists: ${DOCKERBOX_IF}, skipping creation"
     fi
 
-    check_configuration ${CONFIG}
+    check_configuration "${CONFIG}"
 
     nat_ip="10.0.0.1"
     nat_mask=24
 
     log info "Pulling options from configuration file"
-    . ${CONFIG}
+    . "${CONFIG}"
 
-    ${IFCONFIG} ${DOCKERBOX_IF} inet ${nat_ip}/${nat_mask} 2>&1 | capture_output debug ifconfig
+    ${IFCONFIG} "${DOCKERBOX_IF}" inet "${nat_ip}/${nat_mask}" 2>&1 | capture_output debug ifconfig
 }
 
 destroy_bridge() {
     if has_bridge_interface; then
         log info "Destroying bridge interface: ${DOCKERBOX_IF}"
-        ${IFCONFIG} ${DOCKERBOX_IF} destroy 2>&1 | capture_output debug ifconfig
+        ${IFCONFIG} "${DOCKERBOX_IF}" destroy 2>&1 | capture_output debug ifconfig
     fi
 }
 
@@ -209,7 +209,7 @@ create_tap() {
     if [ -z "${_tap}" ]; then
         _tap="$(${IFCONFIG} tap create up)"
         log info "Linking tap interface to ${DOCKERBOX_IF}: ${_tap}"
-        ${IFCONFIG} ${DOCKERBOX_IF} addm "${_tap}" 2>&1 | capture_output debug ifconfig
+        ${IFCONFIG} "${DOCKERBOX_IF}" addm "${_tap}" 2>&1 | capture_output debug ifconfig
     else
         log warn "Linked tap interface already exists: ${_tap}, skipping creation"
     fi
@@ -221,7 +221,7 @@ destroy_tap() {
 
     if [ -n "${_tap}" ]; then
         log info "Destroying linked tap interface: ${_tap}"
-        ${IFCONFIG} ${_tap} destroy 2>&1 | capture_output debug ifconfig
+        ${IFCONFIG} "${_tap}" destroy 2>&1 | capture_output debug ifconfig
     fi
 }
 
@@ -257,7 +257,13 @@ check_vmm() {
 }
 
 get_vm_manager_pid() {
-    ${PGREP} -fx "daemon: ${VM_MANAGER_DAEMON_ID}\[[0-9]*\]"
+    local _pid
+    _pid="$(${PGREP} -fx "daemon: ${VM_MANAGER_DAEMON_ID}\[[0-9]*\]" || true)"
+    if [ -z "${_pid}" ]; then
+        log error "Failed to get VM manager PID"
+        return 1
+    fi
+    echo "${_pid}"
 }
 
 vm_manager() {
@@ -267,18 +273,18 @@ vm_manager() {
 
     log info "Starting dockerbox"
 
-    check_configuration ${CONFIG}
+    check_configuration "${CONFIG}"
 
     cpu=1
     memory=512M
 
     log info "Pulling options from configuration file"
-    . ${CONFIG}
+    . "${CONFIG}"
 
     check_vmm
     check_nat
 
-    if [ ! -f ${DISK_IMAGE} ] || [ ! -f ${DEVICE_MAP} ]; then
+    if [ ! -f "${DISK_IMAGE}" ] || [ ! -f "${DEVICE_MAP}" ]; then
         log error "Disk image not installed"
         log info "Please run 'service dockerbox fetch'"
         exit 1
@@ -306,7 +312,10 @@ dockerbox_start() {
     local _run_console="${1:-}"
     local _pid
 
-    _pid="$(get_vm_manager_pid)"
+    _pid="$(get_vm_manager_pid)" || {
+        log error "Failed to start dockerbox: Could not get VM manager PID"
+        exit 1
+    }
 
     if [ -n "${_pid}" ]; then
         log warn "Guest is already run by PID ${_pid}, left intact"
@@ -324,7 +333,10 @@ dockerbox_start() {
 
 dockerbox_stop() {
     local _pid
-    _pid="$(get_vm_manager_pid)"
+    _pid="$(get_vm_manager_pid)" || {
+        log error "Failed to stop dockerbox: Could not get VM manager PID"
+        exit 1
+    }
 
     if [ -n "${_pid}" ]; then
         log info "Stopping guest ${DOCKERBOX_VM}, managed by PID ${_pid}"
@@ -364,7 +376,10 @@ dockerbox_status() {
 
     log info "Begin: dockerbox status"
 
-    _pid="$(get_vm_manager_pid)"
+    _pid="$(get_vm_manager_pid)" || {
+        log error "Failed to get dockerbox status: Could not get VM manager PID"
+        exit 1
+    }
 
     if [ -n "${_pid}" ]; then
         output "dockerbox is running as pid ${_pid}"
@@ -380,15 +395,15 @@ dockerbox_fetch() {
     DISK_IMG_SUM=78512a9e7c61371124db962ee0eceb83a5994a784290c33c25e798a9ea98e480
     DISKVERSION=0.1.1
     log debug "Fetch dockerbox disk image"
-    fetch -o /tmp https://github.com/leafoliage/freebsd-dockerbox/releases/download/disk-${DISKVERSION}/dockerbox-img-${DISKVERSION}.tar.zstd
+    fetch -o /tmp "https://github.com/leafoliage/freebsd-dockerbox/releases/download/disk-${DISKVERSION}/dockerbox-img-${DISKVERSION}.tar.zstd"
     if [ "$(${SHA256} --quiet /tmp/dockerbox-img-${DISKVERSION}.tar.zstd)" != "${DISK_IMG_SUM}" ]; then
         ${RM} /tmp/dockerbox-img-${DISKVERSION}.tar.zstd
         log error "Dockerbox image checksum unmatch"
         exit 1
     fi
-    ${TAR} -C /usr/local/share -xf /tmp/dockerbox-img-${DISKVERSION}.tar.zstd
-    ${MV} /usr/local/share/dockerbox-img-${DISKVERSION} /usr/local/share/dockerbox
-    log info "Dockerbox disk image installed to /usr/local/share/dockerbox"
+    ${TAR} -C /usr/local/share -xf "/tmp/dockerbox-img-${DISKVERSION}.tar.zstd"
+    ${MV} "/usr/local/share/dockerbox-img-${DISKVERSION}" "${GUEST_ROOT}"
+    log info "Dockerbox disk image installed to ${GUEST_ROOT}"
 }
 
 #[ "$0" != "${SCRIPT}" ] && return 0
